export const SEPARATOR = "──────────────────────────────────────────";

export function printHelpAi(command = "npx @withfrontmatter/solo-check"): void {
  console.log("");
  console.log("Frontmatter Solo — AI Workflow");
  console.log(SEPARATOR);
  console.log("");
  console.log("Use an AI assistant to fix Solo compatibility errors");
  console.log("or generate Solo-compatible Astro code from scratch.");
  console.log("");
  console.log("Works with: Claude, ChatGPT, Cursor, Copilot, or any");
  console.log("coding assistant that accepts a system prompt.");
  console.log("");
  console.log(SEPARATOR);
  console.log("");
  console.log("  The generated code must pass:");
  console.log("    frontmatter solo:validate");
  console.log("");
  console.log("  Fix an incompatible project");
  console.log("");
  console.log("  1. Open fm-skill.md as your AI system prompt");
  console.log("  2. Paste prompts/fix-project.md");
  console.log("  3. Provide your Astro files");
  console.log(`  4. Re-run: ${command}`);
  console.log("");
  console.log("  Convert HTML or Figma output to Solo-compatible Astro");
  console.log("");
  console.log("  1. Open fm-skill.md as your AI system prompt");
  console.log("  2. Paste prompts/figma-to-astro.md");
  console.log("  3. Provide your HTML input");
  console.log(`  4. Validate: ${command}`);
  console.log("");
  console.log("  Audit before fixing");
  console.log("");
  console.log("  1. Open fm-skill.md as your AI system prompt");
  console.log("  2. Paste prompts/audit.md");
  console.log("  3. Provide your Astro files");
  console.log("  4. Review the report, fix, then re-run");
  console.log("");
  console.log(SEPARATOR);
  console.log("");
  console.log("Files included in this package:");
  console.log("");
  console.log("  fm-skill.md                strict Solo-compatible AI skill");
  console.log("  README_AI.md               AI workflow overview");
  console.log("  prompts/fix-project.md     fix an incompatible project");
  console.log("  prompts/figma-to-astro.md  convert HTML to Solo Astro");
  console.log("  prompts/audit.md           audit before validation");
  console.log("");
  console.log("Get files:");
  console.log("  github.com/withfrontmatter/solo-check");
  console.log("");
  console.log(SEPARATOR);
  console.log("");
  console.log("Once your project passes validation:");
  console.log("");
  console.log("  frontmatter solo:build --adapter twig");
  console.log("  frontmatter solo:build --adapter php");
  console.log("");
  console.log("  -> frontmatter.tech/solo");
  console.log("");
}
